### ISSUE TITLE
Commands displayed locally

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#1]
When a chat command is used, it is shown on the players screen in addition to the desired output.

**Comment by midspace** [comment]
On the MessageEntered event handler,
MyAPIGateway.Utilities.MessageEntered += Utilities_MessageEntered;

private void Utilities_MessageEntered(string messageText, ref bool sendToOthers)
{
}

The sendToOthers parameter determines if the chat command entered is echoed back or not.

**Comment by jpcsupplies** [comment]
so where i use
            MyAPIGateway.Utilities.MessageEntered += gotMessage;

to trigger
       private static void gotMessage(string messageText, ref bool sendToOthers)
        {
            if (processMessage(messageText)) { sendToOthers = false; }
        }

should I also somehow trigger this, or trigger this instead of the above?
       private void Utilities_MessageEntered(string messageText, ref bool sendToOthers)
        {
            if (processMessage(messageText)) { sendToOthers = false; }
        }
although potentially i am double handling processmessage if i use both.. or is my gotMessage already correct, just not returning true for whatever reason?
Going to assume the later - since your handler and mine are almost identical.. ill examine if my return trues are all in the right place or missing..

**Comment by midspace** [comment]
Either. You don't need both.

**Comment by jpcsupplies** [comment]
Nailed it, i had some return falses where i shouldnt have..

1 bug down..! :)
