### ISSUE TITLE
Projected Logic issues: New players balance. 

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#10]
If a new player joins, and uses the bal command to check someone else's balance, or any other invalid command, it probably wont create their default balance.  This is a non issue if:

When they first check their own balance or get sent (or try to send) money it creates it then.

**Comment by SaltPepp** [comment]
I have found a ClientJoined, ClientKicked, ClientLeft, HostLeft and ChatMessageReceived events that we can subscribe to under MyMultiplayerBase. I'm not sure if these events are accessible so we are going to create a test mod to see if they are accessible.

**Comment by midspace** [comment]
Client has a balance created by the Server when they join.
Fixed in https://github.com/jpcsupplies/Economy_mod/commit/15cc91a5254ffa033359c463ee2937748ffd94c1
