### ISSUE TITLE
[bug] Worth command seems to be over inflating value significantly.

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#102]
I've noticed this anomaly myself, but player contrastX pointed it out pretty well -

Basically the value reported by worth seems to be unusually high.

contrastX gave a player 20000 to build a small ship,  On valuing it with worth, the ship was reportedly worth 3.2million.

I checked a few of my own vehicles and buildings and they report values between 4 billion and 6 trillion.. which sounds a bit high...

**Comment by jpcsupplies** [comment]
Testing on sever: build a base of 2 blocks and a crate, worth sounds about right, added some ice that valued correctly too it appears..

Then i checked survey ship.  Ship value about 5173,000,000.. cargo value 87,000,000,000

i have 219,000 iron ingots.. and various amounts under 2000 of various misc components..
so its possible the component value going wrong somewhere.  Ive examined the code and nothing odd jumps out at me, you appear to have disabled oxygen and hydrogen valuation although you go through the motions..   ill keep experimenting

**Comment by midspace** [comment]
I fixed a bug in /sell which was duplicating the value of the inventory when a rotor or piston was involved.

But I haven't seen anything like that in /worth.

**Comment by midspace** [comment]
Recheck the figures now.

**Comment by jpcsupplies** [comment]
Seems to look correct now.  Im getting ships in millions and hundreds of thousands instead of billions
