### ISSUE TITLE
Clientconfig.MissionID not saving between sessions

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#120]
missionID is working as a client side global, but doesn't appear to be saving in the players balance record.

If i increment the mission id and save and/or quit then reload the world, it reverts to 0.

The record does exist in data however. It just stays as 0 for some reason.

Manually editing the field to 3 still loads as 0, although it remains 3 in the file.

It just appears the field never updates during save/load

**Comment by midspace** [comment]
Not so much as a bug, as just not implemented as yet.
Player actions or requests need to be sent back to the server, which will update the Mission Id for that player, which will then send it to the player.

**Comment by jpcsupplies** [comment]
refer #132
