### ISSUE TITLE
Release for 1.123

### ISSUE THREAD

**Issue by midspace** [jpcsupplies/Economy_mod#122]
The economy mod with its current code needs to be published.
The public mod is currently broken, and needs to be updated with the working code in GitHub.

**Comment by midspace** [comment]
Complaints about it not working.
http://steamcommunity.com/sharedfiles/filedetails/?id=504209260

However I'm testing it locally, and it's fine.

I think there is something else going on here.

**Comment by midspace** [comment]
I think there is an incompatibility with the binary file that is generated when the game compiles the mod code.
There are two methods to resolve this.
Have the user's try to clean their Bin64 or Bin folder manually.

Or, republish the mod. Republishing the mod with a minor change (like the version number), should force it to recompile the binary in game for them.

**Comment by midspace** [comment]
Correction, it's not in the Bin folder any more.
It's in the User's folder now with the downloaded mods.
%AppData%\SpaceEngineers\Mods\

The downloaded mod:
504209260.sbm

The compiled script code:
504209260.sbm_Economy.scripts

**Comment by midspace** [comment]
Okay, I've put a comment to the Steam mod, recommended to delete.
We'll see how it goes.

**Comment by jpcsupplies** [comment]
sorry only just got this notification now..  stupid overheating laptop..

just blip me in steam if you need me to push out a release..  i was holding off release until we had player owned trade for people to play with..

**Comment by jpcsupplies** [comment]
I probably should give you some sort of backdoor access to my steam account since steam seems to currently have a bug where only the founder on a team can push updates to mods..   unless there is another way (steam cmd?)
