### ISSUE TITLE
TODO: new video showing latest features..  

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#131]
Ok so now i need a video explaining admin commands and player trade zones
anything else i missed?  Hud intro maybe tho its still pretty basic.

**Comment by midspace** [comment]
need to use `/econfig enablePlayerTradeZones on` first.
It is disabled by default currently.

**Comment by jpcsupplies** [comment]
Ok, video done, missed some minor stuff, but it took all day as it was :)
https://www.youtube.com/watch?v=zdnNRZPOMs4
I should probably close this now.
