### ISSUE TITLE
bug - hud updates - reset or neg payments dont update hud etc

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#137]
just noticed hud didnt update after using admin pay and reset commands nor did it update on /bal or chat  need to investigate

* [x] Reset command not updating hud
* [x] bal command not updating hud
* [x] hud doesnt immediately update on receving funds
* [x] gps on hud doesnt update automatcially

**Comment by jpcsupplies** [comment]
Hud also wont update immediately on player recieving funds, but this is a known issue.  Need to work out a workaround for that later.

**Comment by jpcsupplies** [comment]
hmm if i use a timer i could have it check current pos vs the pos in the hud and do nothing if it is less than 1.. same timer could be used for checking pos vs mission objective coords (thinking out loud)

**Comment by midspace** [comment]
Please retest all of the above issues and confirm they are working.

**Comment by jpcsupplies** [comment]
All good here, tho i had to test under dev as my internet is shaped and cannot download stable atm.
Good work.
