### ISSUE TITLE
[player request enh]  Method to break up the LCD list across more than one LCD

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#149]
A player on a server which has a ton of mods that results in more components than a single LCD can legibly show on a single screen has asked if we have any way to allow components to be spread out on more than one screen.

Two possible solutions might be:

- Adding a auto-scroller (bit complicated for my skill, not really friendly to read, look cool tho)
- Adding a tag of some sort that begins the list at #'th line.   Eg components 20 shows only components from the 20th item down on the LCD

I can possibly hack together a #'th line solution, but there may be a better way.  What are your thoughts @midspace ?

**Comment by midspace** [comment]
I did consider following what MMaster did, creating this group linking, "!LINK:GROUP NUMBER"
http://steamcommunity.com/sharedfiles/filedetails/?id=407158161

But it's a level of complexity that is not required for a fixed system.
The plan was to simply specify the Page number.
The line number would be calculated automatically from the text size. The rest would fall into place easily.
ie.,

"components P1"

"components P2"

"components P3"

**Comment by jpcsupplies** [comment]
Think i've got a super simple solution, just committing at the moment.

Adds keyword #  
so 
```
[economy]
* #50
```
Would display only from item 50 onwards.

Crazy simple and even i could code it :)

**Comment by jpcsupplies** [comment]
Hows that look, works for me when i test it, but it may be less than entirely elegant.

**Comment by jpcsupplies** [comment]
Ok i've disabled my mission tech demo with a || false and pushed the version with this to public.. god help us all i put my code in the wild lol

**Comment by jpcsupplies** [comment]
If the code seems ok (ie wont burn any houses down) or if you trim it down to something more efficient feel free to close this issue, otherwise ill close it when i hear from you next or I have double checked this build is behaving ok on ramblers..    i am also ordering some C# teach yourself books.. so if i learn anything useful I might be less incompetent in c# than usual in a month or so lol.

**Comment by jpcsupplies** [comment]
All seems well on ramblers for this feature.
