### ISSUE TITLE
Storage path changes

### ISSUE THREAD

**Issue by midspace** [jpcsupplies/Economy_mod#150]
We have access to new methods to store files under the WorldStorage path, instead of in the ModStorage path.

ReadFileInWorldStorage
WriteFileInWorldStorage
FileExistsInWorldStorage
DeleteFileInWorldStorage
ReadBinaryFileInWorldStorage
WriteBinaryFileInWorldStorage

We'll need to write some functionality to read from the existing file locations, before writing them to the new file locations, then deleting them from the old locations.

**Comment by jpcsupplies** [comment]
6 days ago? wierd I checked more recently than that i thought.

Once we get the mission scripting system working will this allow admins to save mission scripts in the same folder as the main map?   Was just thinking for portability admins might want everything in the one place.. particularly in light of less than friendly pathing used by hosting companies.
