### ISSUE TITLE
[bug] /gps add  now creates a gps nowhere near the player!?

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#152]
As of one of the last few updates (not sure exact one only just noticed it)  my quickgps system seems to add the gps point at some totally bizarre location.    Did keen change the order from xyz to yxz or something.. not sure..  whatever it is, instead of the gps appearing near the player, it was appearing several kms away from the player instead.

Either that or i just made some stupid mistake somewhere that didn't manifest until now.

**Comment by midspace** [comment]
Let's play a game, called one of these letters does not match.
`location.X = x; location.Y = y; location.Z = y;`
https://github.com/jpcsupplies/Economy_mod/blob/master/Economy/Data/Scripts/Economy.scripts/EconConfig/HudManager.cs#L417

**Comment by jpcsupplies** [comment]
stupid mistake it is then...   probably either my laptop touch pad which i cannot turn off and randomly moves my cursor or a cat on keyboard..  and I hit ctrl-Z one too many times, or I simply suck! lol..

Probably the later.
