### ISSUE TITLE
Thumbnail image

### ISSUE THREAD

**Issue by midspace** [jpcsupplies/Economy_mod#26]
Need a cool/nice thumbnail image for the mod.
You know the term "first impressions"?
Well, your thumbnail is the first impression.

The current thumbnail is this: https://github.com/jpcsupplies/Economy_mod/blob/master/Economy/thumb.jpg
![Image](https://raw.githubusercontent.com/jpcsupplies/Economy_mod/master/Economy/thumb.jpg)

**Comment by jpcsupplies** [comment]
Good point..    hmmm   now i need something cool and not breaking anyones copyright..
a screenshot of a blue mining base.. with er...  some dude under a money shower ?   ... open to ideas here...

**Comment by jpcsupplies** [comment]
OK ive taken a shot in game and edited in my daughter dressed in a cheesy space suit holding a money bag!   have to do for now...
