### ISSUE TITLE
TODO: command to lookup the buy/sell price of a given item in the price table

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#30]
Need a command where you can lookup the price of an individual items buy and sell price, or optionally list the entire table itself in a mission window.

Could be expanded to act as a calculator - eg
/value 20 gold ingot

responds something like:
20 gold is worth 2000 (selling 20 at 100 each)  

plus perhaps a reference to the buy price too, since selling to the server will pay less than what it costs to buy or buy back.     eg,  miners sell gold to server at 95,  but it costs 100 to buy (or buy back)    that way the idea of it being for trading is maintained, as profit margins are enforced

**Comment by jpcsupplies** [comment]
Looks like this one is done!  
Displaying entire table in a window is a possibility too, but i think is not necessary here; as the entire price table will likely be added under another command as part of the process of the buy/sell system.

**Comment by midspace** [comment]
I need to make sure the MarketStruct will serialize in a message so we can send a whole list through to a client, otherwise we'll have trouble displaying the right localized name for components.

**Comment by jpcsupplies** [comment]
when we come to it, in a pinch couldnt we run a loop to build a string seperated by newlines of all the entries anyway, and just throw that to the mission window?   Assuming newlines are treated as new line in mission window, ive not messed around with the windows a great deal yet.

**Comment by jpcsupplies** [comment]
How are we with this issue?  Value command works as far as I can see; you wanted to cater for localized names better tho?   Is it safe to close this issue?  Worst case scenario log a localisation issue later?

**Comment by jpcsupplies** [comment]
Actualy we have a localisation issue open already at #40  closing this one as a duplicate.
