### ISSUE TITLE
TODO: allow players to sell items to server

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#31]
Need the ability for a player to sell a chosen item and qty back to the server in exchange for its listed value

eg
/value iron ore  
(replies 2ea)
/sell 20 iron ore
(removes 20 iron ore from their inventory and pays them 40)

optionally the amount they get paid is deducted from the balance of an NPC player in the bank file
eg Merchant
So we will need to create a fake bank entry for the "merchant"  this will be paid to and drawn from when players transact with the server.   Once we transition to global commodity market the merchant account will behave like a trader that always lists at the same price (based on price table) that way at least one merchant is always active even if its the server itself

long term keep track of available supply of resources too in order to transition to the global market later

**Comment by jpcsupplies** [comment]
Making painfully slow progress..    but with two kids running around screaming its a wonder if even loaded without errors lol..   

The create NPC account bit works tho, but the fact i used the reset command logic makes it a rather messy bit of code.

**Comment by jpcsupplies** [comment]
Ok, code should make some sort of sense now.
I am just pondering if i should focus on player to player trade first, or the player to NPC table.

Both seem similar complexity.
/sell all iron 0.5 "Screaming Angel"
logic
- check valid ore / command line options
- check player is nearby
- send them a request to sell - player types /sell approve or deny or times out, or seller /sell cancel
-if approved make relevant changes to bank balance and carried items

/sell all iron
logic
- check valid ore / command line options
- check NPC trade region nearby
- transfer goods to price table
- make relevant changes to NPC balance and carried items

**Comment by jpcsupplies** [comment]
@midspace Having trouble building my sell regex - refer notes in code - can i get an assist :)

**Comment by midspace** [comment]
Sorry, I've been vury busy building a new mining ship on the server.
BTW, some played demolition derby on the inside of the station. Lots of ship parts drifting about.
I'll have a look at it tomorrow evening. Work has me busy this week.

**Comment by jpcsupplies** [comment]
oh well at least players cant complain we didnt leave enough spare parts..
on the up side the /accounts list will probably tell us who logged on recently.....

**Comment by jpcsupplies** [comment]
any way we can use this to discriminate material type, for our qty checks?
var physicalItems = MyDefinitionManager.Static.GetPhysicalItemDefinitions();

**Comment by midspace** [comment]
> any way we can use this to discriminate material type, for our qty checks?

yes. To a degree we're already checking the material types in the MessageSell.ProcessServer().
https://github.com/jpcsupplies/Economy_mod/blob/master/Economy/Data/Scripts/Economy.scripts/Messages/MessageSell.cs

I intend to move those validations into ProcessServer(), as this will better encapsulate the functionality if we extend it later into an API, and it reduces the potential for hackers misusing it, as it will do it's own validation instead of relying upon validation prior to it running.

**Comment by midspace** [comment]
I've like to move the RangeCheck into the ProcessServer also.

**Comment by SaltPepp** [comment]
I've been thinking....
An idea I thought of is that you can trade items for items. This could be a bool setting if true, this feature is enabled.

Sent from my Windows Phone
________________________________

**Comment by jpcsupplies** [comment]
Game already works like that now in effect @SaltPepp  without an economy players would trade materials with each other.  However the economy mod can work similarly; you just send an offer to sell goods to a player for free, then hope they send the goods free back in return.  The idea had occurred to me in passing.   In financial market terms its considered barter or tether type trade. 

re: rangecheck @midspace   I always assumed we would be moving that stuff out of the main file,  as we did with the other commands,  I considered making it in another file, but while it is a placeholder didnt think it would matter yet; and was undecided which would be the best place as rangecheck can be used for other stuff too potentially.

**Comment by jpcsupplies** [comment]
All underlying error checks, pricing lookups, item transfers, and payment technologies for this command are now in place.   Sell command to sell to server is not fully operational within the stated aims of this milestone.  Good Work Everyone.   May still be bugs, but basic functionality is ready to go.
