### ISSUE TITLE
ENH: HUD? 

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#37]
What are your thoughts on this? -
In line with the role play elements of this being a "trade interface" is it worth looking into adding a HUD?  Like top left or right displays player balance, and later on maybe basic stats on how many items are for sale/on order/fulfilled/active contracts.

Eg: 
Balance: 100 | Faction: UFP |  Ordered: 3 / Filled: 75% | Selling: 2 / Sold 50% |
 Contracts Held: 2 / Available: 4 | Next deadline 00h:09m:04s

Or something prettier or less cluttered. Maybe offer players commands to turn on or off particular hud info.

The GPS mod in the autopsy list seemed to work well with no lag, and it polled the players location and updasted an on screen  hud.  We dont need gps coords anymore thanks to gps points obviously,  but the info we have would require much less polling that coords so it shouldnt be causing physics lag..
- [x] Balance
- [x] Location
- [x] Faction ID
- [x] Trade zone ID
- [x] Mission
- [ ] mission chain progress /contracts/deadlines
~~- [ ] % full inventory~~ (built into keen vanilla hud now)

**Comment by midspace** [comment]
I think I mentioned this, but I've been considering something like this for my Scan mod.

Currently, most LCD mods work by using the Programmable Block.
But they have the convenience of accessing the Ingame Api, which gives them plenty of access to information about the Grid that the LCD is attached to.

The problem is once you move into the Mod API Script (not Ingame) to get access to more information, your PB LCD no longer has access to this information.
Ingame cannot access Mod API.

Now, what you could do is write a Custom LCD which would have it's own logic to access the Mod API Script code. The logic would run on the server I believe, and not the clients (I haven't tested this. I'm assuming, but I hate to assume).
Except that there is a limitation. You can only have 1 Custom block of any given type that accesses Mod API code.
If there is another Mod out there written as a customized LCD, it will conflict with ours, and only one of them will run.
There are a a couple of attempts on the Keen Git source to address this issue, but Git PR's are on hold at the moment, so there is no fix in sight for this issue.

The alternative I've been considering is based on the code we have added for the Client/Server interaction.
We could add a command for a user use when pointing at a LCD, which will connect the LCD to the 'Merchant Network' (just made that up now).
What it does, is tells the Server code to track that particular LCD block, and update it with the trade interface at regular intervals.
As the Server has all the information it needs, and the server itself will be aware if information changes, it can update the LCD when it is ready.
We can also enforce delays, to prevent updating the LCD too often, which is usually the cause of Server's slowing down (run-away mods doing too much processing).

Of course we need to add in various checks, like if the LCD is hacked, or destroyed to remove it from the Server update list.
If it's turned off, then it stops updating.

**Comment by jpcsupplies** [comment]
I was thinking more an on-screen hud  (your scanner could do that too actually -eg
-------------------------------|-------------------
|
|
|
-
|

the pipe being the direction of the detected vessel.. in effect a crude target lock radar hud

Not sure if you have been on a server while GPS mod is running but it displays on the top of the game screen in the middle your current coordinates.
I was thinkning use the same top row for some sort of economic summary.

But using LCDs for detailed info on trades and so on, would be great idea too..   might even be able to use the picture display function to show a pic of the item lol
Use phoenix's trick (from FTL MOD)  of scanning for objects with a particular name (in his case FTL) and use that for things like deciding which way is the front, what sound block to play the jumping sound from, what LCD to display jump statistics on etc

**Comment by midspace** [comment]
There was one thing someone showed me a while ago, was a PB block and script, with a Control Panel operating in conjunction with a LCD.
The Control Panel's 4 buttons were like a Mobile phone. Up/Down, Enter/Back.
It allowed to scroll through an interactive menu on the LCD, and was very responsive.

**Comment by jpcsupplies** [comment]
The in game scripting can do some crazy stuff on lcds,  in my periodic /tps 's to locate derelicts or space junk to clean up, ive come across some ships and bases running some pretty crazy data read outs on their LCD screens.

**Comment by jpcsupplies** [comment]
Hmmm - I might just make a basic hud that displays player balance(using our currency type string), faction, and trade network...

Eg.     Blue Mining Inc Trade Network: Balance: 100 Credits, Employed by BLU
"XX(name) Trade Network:   Balance YY ZZ(currency unit),  Employed by YZ(faction)"

**Comment by jpcsupplies** [comment]
Oooo something useful -   Have the hud show all available storage/mining space vs how full that space is..
eg.
Blue mining inc trade network.  Balance 100 Credits.  Cargo used: 34000 / 48000. Employed at BLU

**Comment by jpcsupplies** [comment]
Note to self use client init to set header, then update message class to update balance

**Comment by midspace** [comment]
I want to say that `MyAPIGateway.Utilities.GetObjectiveLine()` should be only used for mission objectives, not for displaying status messages.
Short term, quest like objectives that are only there until you complete the quest.
It's a missuse of the API for something that should be used for missions.

Unfortunately, there isn't any other API for a persistent on screen text.

I did implement this particular API for my derelict scanner, as a mission oriented task.
You set an objective to a specific derelict. It provides directions on the objective line as you approach.
Once you reach it the objective is completed. If you exit the cockpit, the objective is cancelled.

**Comment by jpcsupplies** [comment]
Well the hud sorta works, hopefully i can use it for holding mission objectives later.  Like deliver x to y type stuff..   just for some reason where i try to grab the bank balance gives me some totally wacky field instead of the balance.    

Only otherways to put stuff on screen is periodic polls and use chat text.
The mission windows are (mis?)used similarly at the moment anyway.

**Comment by jpcsupplies** [comment]
Would it be worth asking keen about adding some sort of modapi "writepos(string,row,column)"  facility to the game?   (i am surprised there isnt actually)

**Comment by jpcsupplies** [comment]
This code has a section that displays a cargo graph similar to what I am trying to do in the hud - any chance of adapting this for the cargo readout  on our hud?

`const string SHIPNAME = "My Ship";
const string VER = "SHIPDOS 0.33";
const bool EMERGENCY_DAMPENERS = true;

void Main(string argument) {

  IMyTextPanel screen = (IMyTextPanel)GridTerminalSystem.GetBlockWithName("LCD");
  if (screen == null) { throw new Exception("No screen present"); }
  IMyTextPanel oxyscreen = (IMyTextPanel)GridTerminalSystem.GetBlockWithName("LCD-Oxy");

  ScreenHelper scr = new ScreenHelper(screen, 36, 17);
  MShip myShip = new MShip(GridTerminalSystem);
  scr.setContent(myShip);
  scr.Draw();

  if (oxyscreen != null) {
    ScreenHelper oxyscr = new ScreenHelper(oxyscreen, 36, 17);
    oxyscr.setOxygenTankContent(myShip);
    oxyscr.Draw(false); 
  }

}
    
public class MShip {    
  public string shipName;    
  public float batteryLevel;   
  public float cargoLevel; 
  public IMyGridTerminalSystem gts;   
  public string control;  
  public bool dampeners; 
  public bool docked;  
  public IMyShipController theHelm;
  public float oxygenLevel;
  public float[] oxygenTanks;

  public MShip(IMyGridTerminalSystem gts) {         
    this.gts = gts;   
    this.shipName = SHIPNAME;    
    this.batteryLevel = getBatteryLevel(); 
    this.cargoLevel = getCargoLevel();     
    this.oxygenLevel = getOxygenLevel();
    getCockpitDetails(); 
    this.docked = checkDockingStatus(); 
  }
   
  public float getOxygenLevel() {
    List<IMyTerminalBlock> tanks = new List<IMyTerminalBlock>();
    gts.GetBlocksOfType<IMyOxygenTank>(tanks);
    IMyOxygenTank tank;
    oxygenTanks = new float[tanks.Count];

    float level = 0;
    for (int i=0; i<tanks.Count; i++) {
      tank = tanks[i] as IMyOxygenTank;
      level += tank.GetOxygenLevel();
      oxygenTanks[i] = tank.GetOxygenLevel();
    }
    if (tanks.Count > 0) { return level / tanks.Count; }
    return 0;
  }

  public float getBatteryLevel() { 
    List<IMyTerminalBlock> batteries = new List<IMyTerminalBlock>();    
    gts.GetBlocksOfType<IMyBatteryBlock>(batteries);    
    IMyBatteryBlock battery;  
    float currentBatteryPower = 0;    
    float maxBatteryPower = 0;  
    for (int i=0; i<batteries.Count; i++) {   
      battery = batteries[i] as IMyBatteryBlock;   
      currentBatteryPower += battery.CurrentStoredPower;        
      maxBatteryPower += battery.MaxStoredPower;  
    }   
    if (maxBatteryPower != 0) { return currentBatteryPower/maxBatteryPower; }  
    return 0; 
  } 
 
  public float getCargoLevel() { 
    float usedStorage = 0, totalStorage = 0;    
    List<IMyTerminalBlock> containers = new List<IMyTerminalBlock>();     
    gts.GetBlocksOfType<IMyInventoryOwner>(containers);     
    for (int i=0; i < containers.Count; i++) {     
      if (containers[i] is IMyCargoContainer) {     
          usedStorage += (float)containers[i].GetInventory(0).CurrentVolume ;     
          totalStorage += (float)containers[i].GetInventory(0).MaxVolume;     
      }     
    }    
    if (totalStorage != 0.0) { return usedStorage/totalStorage; }    
    return 0; 
  } 
 
  void getCockpitDetails() { 
    this.control = "VACANT"; 
    this.dampeners = false; 

    List<IMyTerminalBlock> controllers = new List<IMyTerminalBlock>();  
    gts.GetBlocksOfType<IMyShipController>(controllers);  
    IMyShipController controller;
  
    for (int i=0; i<controllers.Count; i++) {  
      controller = controllers[i] as IMyShipController;  
      if (controller.IsUnderControl) { this.control = "CONTROLLED"; }  
      if (controller.DampenersOverride) { this.dampeners = true; }  
    }  
 
    if ((EMERGENCY_DAMPENERS) && (this.dampeners == false) && ( this.control != "CONTROLLED")) {
      List<IMyTerminalBlock> econtrollers = new List<IMyTerminalBlock>(); 
      gts.GetBlocksOfType<IMyShipController>(econtrollers); 
    
      IMyShipController econtrol;
      for (int i=0; i<econtrollers.Count;i++) {
        econtrol = econtrollers[i] as IMyShipController;  
        if (!econtrol.DampenersOverride) {
          econtrol.GetActionWithName("DampenersOverride").Apply(econtrol);
        }
      }
    }
  } 
   
  public bool checkDockingStatus() { 
    List<IMyTerminalBlock> connectors = new List<IMyTerminalBlock>(); 
    gts.GetBlocksOfType<IMyShipConnector>(connectors); 
    IMyShipConnector connector; 
    for (int i=0; i<connectors.Count; i++) { 
      connector = connectors[i] as IMyShipConnector; 
      if (connector.IsLocked) { return true; } 
    } 
    return false;
  } 
 
 
}  

public class ScreenHelper {
  private IMyTextPanel panel;
  private int COLS;
  private int ROWS;
  const int HEADERS = 1;
  const int FOOTERS = 1;
  private string contents;
  private string header;
  private string footer;

  public ScreenHelper(IMyTextPanel panel, int cols, int rows) {
    this.panel = panel;
    this.COLS = cols;
    this.ROWS = rows;  
    this.contents = "";
    this.header = VER;
  }

  public void setContent(MShip ship) {
    const string ON = "ON"; const string OFF = "OFF";
    const string YES = "YES"; const string NO = "NO";
    string dampeners, emergencyDampeners;
    string dockedText;
    if (ship.dampeners) { dampeners = ON; } else { dampeners = OFF; }
    if (ship.docked) { dockedText = YES; } else { dockedText = NO; }
    if (Program.EMERGENCY_DAMPENERS) { emergencyDampeners = ON; } else { emergencyDampeners = OFF; }
    contents = drawBar(ship.batteryLevel, COLS) + " BATT\n";
    contents += drawBar(ship.cargoLevel, COLS) + " CARG\n";
    contents += drawBar(ship.oxygenLevel, COLS) + "OXYG\n";
    contents += "Emergency Dampeners: " + emergencyDampeners + "\n";
    contents += "Dampeners: " + dampeners + "\n";
    contents += "Control: " + ship.control + "\n";
    contents += "Docked: " + dockedText + "\n";
    contents += new String('\n', ROWS-12);
  }

  public void setOxygenTankContent(MShip ship) {    
    this.header = "OXYGEN TANK STATUS";
    contents = "";
    for (int i=0; i < ship.oxygenTanks.Length; i++) {
      contents += drawBar(ship.oxygenTanks[i], COLS) + "\n";
    }
  }

  public void Draw(bool showFooter = true) {
    panel.WritePublicText("", false);
    string line = ""; 
    string dashline = new String('-', 60) + "\n"; 

    panel.WritePublicText(header+ "\n", true);
    panel.WritePublicText(dashline, true);

    panel.WritePublicText(contents + "\n", true);
    if (showFooter) {
      panel.WritePublicText(dashline, true);
      panel.WritePublicText(footer, true);
    }
    panel.ShowPublicTextOnScreen(); 
  }

  public void DrawOxygenTanks() {
    panel.WritePublicText("", false);
    string line = "";
    string dashline = new String('-', 60) + "\n";
    panel.WritePublicText("OXYGEN TANKS\n", true);
    
    panel.ShowPublicTextOnScreen();
  }

  string drawBar(double percent, int width) { 
    string bar = "<"; 
    for (int i=0; i<(width-2); i++) { 
      double barPos = (double)i/width; 
      if (percent >= barPos) { bar += "|"; } else { if (i % 2 == 0) { bar += "''";} } 
    } 
    if ((bar.Length + 1) < width) { bar += "'"; } 
    bar += ">[" + percent.ToString("P0").PadLeft(5) + "]";
 
    return bar; 
  } 

}`

**Comment by jpcsupplies** [comment]
supercede last point to #36
