### ISSUE TITLE
ENH: Default Pricing

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#48]
Although admins will likely tweak this -
For the default RRP price book pricing, if the pricebook has not yet been created;   we should have an internal constant which populates the prices when we do create it so the price table created has plausible pricing.

Examples, 
buy price lower than sell price
weapon related materials more expensive
common materials like stone and iron, less expensive
slightly rare essential materials a little more costly uranium etc 
more rare materials like silicon etc somewhere middle priced
precious metals like gold/silver/platinum more expensive etc

**Comment by jpcsupplies** [comment]
Ice should be costly, say 40 a unit at most.
Gravel and stone really cheap like less than 1 each

**Comment by TheEngineer50** [comment]
There is this:

http://ripexz.github.io/se-trade/

**Comment by midspace** [comment]
The pricing behind http://ripexz.github.io/se-trade/
```
	{"name": "Stone", "type": "raw", "rate": 310},
	{"name": "Iron Ore", "type": "raw", "rate": 500},
	{"name": "Nickel Ore", "type": "raw", "rate": 20},
	{"name": "Cobalt Ore", "type": "raw", "rate": 22},
	{"name": "Magnesium Ore", "type": "raw", "rate": 24},
	{"name": "Silicon Ore", "type": "raw", "rate": 22},
	{"name": "Silver Ore", "type": "raw", "rate": 20},
	{"name": "Gold Ore", "type": "raw", "rate": 20},
	{"name": "Platinum Ore", "type": "raw", "rate": 20},
	{"name": "Uranium Ore", "type": "raw", "rate": 44},

	{"name": "Gravel", "type": "refined", "rate": 279},
	{"name": "Iron Ingot", "type": "refined", "rate": 350},
	{"name": "Nickel Ingot", "type": "refined", "rate": 8},
	{"name": "Cobalt Ingot", "type": "refined", "rate": 6.6},
	{"name": "Magnesium Powder", "type": "refined", "rate": 0.168},
	{"name": "Silicon Wafer", "type": "refined", "rate": 15.4},
	{"name": "Silver Ingot", "type": "refined", "rate": 2.2},
	{"name": "Gold Ingot", "type": "refined", "rate": 0.2},
	{"name": "Platinum Ingot", "type": "refined", "rate": 0.1},
	{"name": "Uranium Ingot", "type": "refined", "rate": 0.308}
```

Ice is not mentioned, so I'm assuming the pricing is a little old, and may actually be dependent on SEToolbox having processed the asteroids to produce breakdowns.
The distribution has changed since Ice was introduced, and will further change when Planets are also added.

**Comment by midspace** [comment]
The problem (considering I'm the SEToolbox author), apart from SEToolbox been unable to read current asteroid file formats, is that SEToolbox can only read asteroid files from 'touched' asteroids. Any procedural generated asteroids that haven't been touched, will not be accessible by SEToolbox.

The way around this, is I could write a quick and dirty mod to actually analyse in game asteroids (same as the /detail command in the Admin mod), and process that data into a text file.
A sample, of say 1000 asteroids, should give us a good idea of the distribution of ores.

**Comment by midspace** [comment]
Refined ore (ingot) values is very dependent on a few of factors.
1. Your refinery speed in game configuration.
2. The individual refinery and arc furnace as each block type has individual refine speed and efficiency rate.
3. And any upgrade modules connected to refinery and arc furnaces.

**Comment by midspace** [comment]
The following figures are from a sample of 235 asteroids (which was all that is available in standard 20Km visibility range), all of which are the procedural asteroids. I have specifically excluded the stock asteroids (centralAsteroid, centralAsteroidmoon, etc.) which are be spawned at origin 0,0,0 and don't necessarily match the same distribution.
I've accumulated the Iron_01 Iron_02, as well the the Ice and Stone into single listings for convenience.

<table>
<tr><td>Ore_name</td><td>deposit count</td><td>cubic meter</td><td>percentage
<tr><td>Cobalt</td><td>60</td><td>4734813.145</td><td>0.61%</td></tr>
<tr><td>Gold</td><td>57</td><td>12194894.57</td><td>1.56%</td></tr>
<tr><td>Ice</td><td>197</td><td>42417884.12</td><td>5.43%</td></tr>
<tr><td>Iron</td><td>235</td><td>401726692.7</td><td>51.41%</td></tr>
<tr><td>Magnesium</td><td>56</td><td>10114095.18</td><td>1.29%</td></tr>
<tr><td>Nickel</td><td>65</td><td>5524046.184</td><td>0.71%</td></tr>
<tr><td>Platinum</td><td>53</td><td>11723734.47</td><td>1.50%</td></tr>
<tr><td>Silicon</td><td>52</td><td>10607933.36</td><td>1.36%</td></tr>
<tr><td>Silver</td><td>58</td><td>6355505.98</td><td>0.81%</td></tr>
<tr><td>Stone</td><td>235</td><td>268914299.9</td><td>34.42%</td></tr>
<tr><td>Uraninite</td><td>98</td><td>7028055.376</td><td>0.90%</td></tr>
<tr><td>Total</td><td>1166</td><td>781341955</td><td>100.00%</td></tr>
</table>

**Comment by midspace** [comment]
I'm doing a full sampling of 50Km currently, which is over 3000 asteroids. It will take some time to analyse all asteroids.
To do this right, I will present the figures based on an average per asteroid, average per 100Km3, and a base weighted average.

**Comment by jpcsupplies** [comment]
stone and iron in equal ratios..  that is a surprise.  But stone is still often a throw away item.. The deposit count compared to cubic meters seems a bit strange tho. 34% vs 51% for same deposit count.
Well this is handy, we can work out some inverse price relationship formula vs 100 maybe,  Eg  uranium 100-0.90 gives us a price of 99.1  that would make cobalt the most valuable ore  weird. Probably need additional conditions, eg divide price by further 10 for items under 30%, and by 100 for items over 30%..
That gives us uranium:  100-0.90 =  99.1.   99.1/10 = 9.91 per kg uranium ore
And stone: 100-34.42=65.58.    65.58/100=0.6558 per kg ore

Actually extrapolating on your detail comment - we could have the server perform an ore analysis on startup, then use some sort of inverse price formula to build the initial price table, which would make it adapt to the available ores in that world at first run to set initial prices.

**Comment by midspace** [comment]
The deposits is pretty irrelevant, as it is just counting how many types or ores per asteroid. Not a useful figure.
These figures I forgot to mention, are just based on asteroids.
The mining rates of each ore differ significantly. I haven't found what eactly the mining rate means in the voxelmaterials.sbc file. So the actual ore in hand after mining will have a different ratio.

Analyzing the asteroids takes some time. i wouldn't recommend it. 3 mins for 100 asteroids on my system.

**Comment by jpcsupplies** [comment]
Owch..   although as a first run (only run once first time mod is loaded) it may work..  but i could just do the calculations and setup a constant in the code when i get a moment

**Comment by midspace** [comment]
Scenario: Asteroids.
Asteroid Amount: Infinite High density.
View Distance: 50 Km

Total asteroids found and analysed: 3,218
Time to process: 1 hour 35 minutes.
Volume of space covered: 5.23599E+14 m³.
Volume of space covered: 523,598.7756 km³.
1 Asteroid per 162,709,377,128.12 m³ of space.
1 Asteroid per 162.71 km³ of space.

__Total overall ore in asteroids__
<table>
<tr><td>Ore name</td><td>meter³</td><td>percentage</td></tr>
<tr><td>Cobalt</td><td>87,643,702.71</td><td>0.96%</td></tr>
<tr><td>Gold</td><td>70,391,905.82</td><td>0.77%</td></tr>
<tr><td>Ice</td><td>322,126,920.07</td><td>3.54%</td></tr>
<tr><td>Iron</td><td>4,959,500,433.90</td><td>54.53%</td></tr>
<tr><td>Magnesium</td><td>97,537,313.26</td><td>1.07%</td></tr>
<tr><td>Nickel</td><td>70,645,362.77</td><td>0.78%</td></tr>
<tr><td>Platinum</td><td>73,006,618.40</td><td>0.80%</td></tr>
<tr><td>Silicon</td><td>88,502,734.55</td><td>0.97%</td></tr>
<tr><td>Silver</td><td>107,905,015.59</td><td>1.19%</td></tr>
<tr><td>Stone</td><td>3,057,583,862.18</td><td>33.62%</td></tr>
<tr><td>Uraninite</td><td>159,950,508.35</td><td>1.76%</td></tr>
<tr><td>Total</td><td>9,094,794,377.62</td><td>100.00%</td></tr>
</table>

__Average ore per asteroid__
<table>
<tr><td>Ore name</td><td>meter³</td><td>percentage</td></tr>
<tr><td>Cobalt</td><td>27,235.46</td><td>0.96%</td></tr>
<tr><td>Gold</td><td>21,874.43</td><td>0.77%</td></tr>
<tr><td>Ice</td><td>100,101.59</td><td>3.54%</td></tr>
<tr><td>Iron</td><td>1,541,174.78</td><td>54.53%</td></tr>
<tr><td>Magnesium</td><td>30,309.92</td><td>1.07%</td></tr>
<tr><td>Nickel</td><td>21,953.19</td><td>0.78%</td></tr>
<tr><td>Platinum</td><td>22,686.95</td><td>0.80%</td></tr>
<tr><td>Silicon</td><td>27,502.40</td><td>0.97%</td></tr>
<tr><td>Silver</td><td>33,531.70</td><td>1.19%</td></tr>
<tr><td>Stone</td><td>950,150.36</td><td>33.62%</td></tr>
<tr><td>Uraninite</td><td>49,704.94</td><td>1.76%</td></tr>
<tr><td>Total</td><td>2,826,225.72</td><td>100.00%</td></tr>
</table>

__Ore per 1 km³ of space__
<table>
<tr><td>Ore name</td><td>meter³</td><td>percentage</td></tr>
<tr><td>Cobalt</td><td>167.39</td><td>0.96%</td></tr>
<tr><td>Gold</td><td>134.44</td><td>0.77%</td></tr>
<tr><td>Ice</td><td>615.22</td><td>3.54%</td></tr>
<tr><td>Iron</td><td>9,471.95</td><td>54.53%</td></tr>
<tr><td>Magnesium</td><td>186.28</td><td>1.07%</td></tr>
<tr><td>Nickel</td><td>134.92</td><td>0.78%</td></tr>
<tr><td>Platinum</td><td>139.43</td><td>0.80%</td></tr>
<tr><td>Silicon</td><td>169.03</td><td>0.97%</td></tr>
<tr><td>Silver</td><td>206.08</td><td>1.19%</td></tr>
<tr><td>Stone</td><td>5,839.56</td><td>33.62%</td></tr>
<tr><td>Uraninite</td><td>305.48</td><td>1.76%</td></tr>
<tr><td>Total</td><td>17,369.78</td><td>100.00%</td></tr>
</table>

__Base weighted average__
<table>
<tr><td>Ore name</td><td>Weight</td><td>MinedOreRatio</td><td>Final Weight</td></tr>
<tr><td>Cobalt</td><td>34.89</td><td>1.00</td><td>34.89</td></tr>
<tr><td>Gold</td><td>43.44</td><td>0.70</td><td>62.05</td></tr>
<tr><td>Ice</td><td>9.49</td><td>0.30</td><td>31.64</td></tr>
<tr><td>Iron</td><td>0.62</td><td>1.00</td><td>0.62</td></tr>
<tr><td>Magnesium</td><td>31.35</td><td>1.00</td><td>31.35</td></tr>
<tr><td>Nickel</td><td>43.28</td><td>1.00</td><td>43.28</td></tr>
<tr><td>Platinum</td><td>41.88</td><td>0.80</td><td>52.35</td></tr>
<tr><td>Silicon</td><td>34.55</td><td>1.00</td><td>34.55</td></tr>
<tr><td>Silver</td><td>28.34</td><td>0.90</td><td>31.48</td></tr>
<tr><td>Stone</td><td>1.00</td><td>1.00</td><td>1.00</td></tr>
<tr><td>Uraninite</td><td>19.12</td><td>0.30</td><td>63.72</td></tr>
</table>

**Comment by jpcsupplies** [comment]
Cobalt	167.39	0.96%	 $9.90 
Gold	134.44	0.77%	 $9.95 
Ice	615.22	3.54%	 $12.37 
Iron	9,471.95	54.53%	 $0.45 
Magnesium	186.28	1.07%	 $12.37 
Nickel	134.92	0.78%	 $9.92 
Platinum	139.43	0.80%	 $9.94 
Silicon	169.03	0.97%	 $9.90 
Silver	206.08	1.19%	 $9.89 
Stone	5,839.56	33.62%	 $0.66 
Uraninite	305.48	1.76%	 $12.43 
NATO_5p56x45mm	0.8 iron 0.2 nikel 02 magne		 $2.35 
NATO_25x184mm	40 iron 5 nickel 3.5magne		 $111.08 
Missile200mm	55iron 7nickel .1uranium .04 plat 1.2magn .2sili		 $96.44 
MetalGrid	12iron 5 nickel 3 cobalt		 $84.78 
Construction	10 iron		 $4.55 
InteriorPlate	3.5 iron		 $1.59 
SteelPlate	21 iron		 $9.55 
Girder	7iron		 $3.18 
SmallTube	5 iron		 $2.27 
LargeTube	30 iron		 $13.64 
Motor	20iron 5 nickel		 $58.70 
Display	1 iron 5 silicon		 $49.97 
BulletproofGlass	15 silicon		 $148.55 
Computer	0.5 iron 0.2 silicon		 $2.21 
Reactor	15iron 20 gravel 5 silver		 $69.56 
Thrust	30 iron 10 cobalt 1 gold .4 plat		 $162.37 
GravityGenerator	600iron 220cobalt 10 gold 5 silver		 $2,600.63 
Medical	60 iron 70 nikel 20 silver		 $919.68 
RadioCommunication	8iron 1 silicon		 $13.54 
Detector	15 nikel 5 iron		 $151.10 
Explosives	2 magnesium .5 silicon		 $74.25 
SolarCell	10 nickel 8 silicon		 $178.44 
PowerCell	10 iron 2 nickel 1 silicon		 $34.29 
AutomaticRifleItem	3 iron 1 nickel		 $11.29 
OxygenBottle	80 iron 10 silver 30 nickel		 $433.07 
WelderItem	5 iron 1 nickel .5 gold		 $17.17 
AngleGrinderItem	3 iron 1 nickel 1 cobalt 1 silicon		 $166.14 
HandDrillItem	20 iron .2 nickel .2 magnes		 $251.80 
Scrap			
Organic

**Comment by midspace** [comment]
There will be plenty of Organic on planets. Insanely high amounts. Its purpose is still unknown and a tightly guarded secret.

> I've not yet built an "ingot" table the prices in my table ar...

I was wondering where that was.


> Apparently you can't build a constant array in c#

Different ways to do this:

```
        #region GetDefaultPriceTable
        public MarketConfig GetDefaultPriceTable()
        {
            const string xmlText = @"<MarketConfig>
  <MarketItems>
    <MarketStruct>
      <TypeId>MyObjectBuilder_AmmoMagazine</TypeId>
      <SubtypeName>NATO_5p56x45mm</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>false</IsBlacklisted>
    </MarketStruct>
    <MarketStruct>
      <TypeId>MyObjectBuilder_AmmoMagazine</TypeId>
      <SubtypeName>NATO_25x184mm</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>false</IsBlacklisted>
    </MarketStruct>
............
  </MarketItems>
</MarketConfig>";
            return MyAPIGateway.Utilities.SerializeFromXML<MarketConfig>(xmlText);
        }
        #endregion
```

**Comment by jpcsupplies** [comment]
Ok, have a csv, xml and xls file with suggested retail pricing..
I used a few calculations, inverse pricing based on ratio or ores in asteroids for a base price, then some additional corrections based on manufacturing losses which gives us ore values vs ingots;  Common ores have an artificially reduced price, rare ores a slightly increased; for components they are flat multiplied by the value of the ingots used in their construction.
Organics, and hydrogen bottle is blacklisted since i have no point of reference on scarcity or components in construction.  (is hydrogen bottle just  a a filled o2 bottle or something else?)

You may be surprised by what the actual value is for some items..  i would double checking a few that cost hundreds but it seems to check out with my data..  

Players are going to love this i think...

**Comment by midspace** [comment]
I always get confused between the buy and sell prices depending on the perspective.
From what you have added, just so we are clear those buy and sell prices are the market prices, not the player prices.
Prices will be swapped around when offered to the player.
Ie, what the market __sells__ at, is what the player __buys__ at.

**Comment by jpcsupplies** [comment]
Think of it from the perspective of the NPC trader.   He sells to the player at $11 for example, and if a player wishes to sell his ore to the NPC, the NPC buys from the player at $10.

So yes what the market /sells/ at is what the player /buys/ at.

.. not related - Given I was basing prices on scarity and production waste with some arbitrary modifiers, I am quite surprised at the pricing I arrived at, have you had a look? Some stuff works out quite expensive due to rarity and waste.  Quite interesting.

**Comment by midspace** [comment]
> Given I was basing prices on scarity and production waste with some arbitrary modifiers, I am quite surprised at the pricing I arrived at, have you had a look?

I haven't had enough time. Working on 3 mods this morning, and I haven't even looked at the game update yet.

**Comment by midspace** [comment]
P.S. The prices are now in.

**Comment by jpcsupplies** [comment]
ahh good work...  ooh ive not checked to see what todays update was at keen ..

**Comment by jpcsupplies** [comment]
Default Pricing now set, and good to go
