### ISSUE TITLE
Dirty fix #32 needs to drop purchase overflow.. to feet and a nitpick

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#57]
#32 is resolved but It needs to test if the inventory is full and drop excess at feet

(also might be a good idea if it says what you just sold just for friendliness but this may come under #40 (localisation)- I just noticed i purchased /buy 10 steel      and it would be nice to say "you just purchased 10 steel plate for $$")

**Comment by jpcsupplies** [comment]
Assigning this to you, cause the code i have for spawning ore in the keen sample mod is obsolete and ive NFI how to do it here :)

**Comment by midspace** [comment]
Is done in https://github.com/jpcsupplies/Economy_mod/commit/6528b64d63e65877b0ad667daf712083ecc2351e
