### ISSUE TITLE
Need a Humorous Promo Movie for the mod.

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#62]
Thinking something like this:
Have a player in the middle of nowhere. Narrator discussing mod.
"Thankyou for choosing to join the Blue Mining Inc Traders Network"
"By joining, you have access to your finances anywhere.."
Player types into his arm (show /bal command on screen, show he has 12 cents) 
(show facepalm animation)
"You can also perform electronic payments immediately - here lets pay this fellow as an example"
(show /pay miner 1000 for starring in this commercial)
(show Blue Mining Has Paid you 1000 for starring in this commercial on screen)
(Show arms up animation)
"using our patented delivery technology we can deliver any order to you immediately"
Player types into his arm (show /buy 1 "Gold Ingot" command on screen)
(use appropriately amusing sound effect such as the sound of someone being hit in the head with a fish)
Show the player being hit in the head with a box. (can use block pasted and thrown from off screen - Switch to inventory view - show items he ordered) 
Then show  player giving the thumbs up.
"We can deliver any quantity you desire.."
Again show player typing in arm - (show /buy 4000 "iron ore" command on screen)
"Just make sure you don't order more than you can handle.."
Drop a giant ore block on his head.. (and the ensuing carnage that follows)
"Lastly if you are unsure of the cost of something you can look it up"
(point at hole from ore with player in it, and show /value medical 1 on screen)

"Once again thank yout for joining our trade network."
(fade to Blue mining inc logo)

**Comment by jpcsupplies** [comment]
Did movie, not as funny as i wanted but shows the basics

**Comment by midspace** [comment]
I meant to ry recording my voice and putting on an accent. I kept forgetting to do it.

**Comment by jpcsupplies** [comment]
We can always do additional movies as we add newer features.. (hmmm what does that remind me of... oh hi keen)
