### ISSUE TITLE
ENH: Request Price List

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#63]
We are now at the point where we need to be thinking how to structure the logic for players to "Request a Price List"
eg /pricelist    or /sell prices  or /buy prices or /value all or /value buy or /value sell  or /value pricelist etc 

This logic has to be flexible enough that it is able to pull out both NPC market pricing, and offer/request pricing in any other markets/trader offers later on.

**Comment by jpcsupplies** [comment]
how about a command that takes the same parameters as the LCDs  but displays the result in a mission screen box?

**Comment by midspace** [comment]
Can do.

**Comment by jpcsupplies** [comment]
That mission window bug is holding this one up.. hmm wonder why they didnt fix it yet.

**Comment by midspace** [comment]
More to the point, what changed to break it?
I tried to look at it last week, but it looks like they're rearranged the code.
I'm assuming the changes resulted in the breakage, but I'm also assuming the changes are to support an editable dialog.

**Comment by midspace** [comment]
the command `/pricelist` was put in prior to release.
https://github.com/jpcsupplies/Economy_mod/releases/tag/1.7A

**Comment by jpcsupplies** [comment]
associated file was missing in git version - had to comment it out
            if (split[0].Equals("/pricelist", StringComparison.InvariantCultureIgnoreCase))
            {
                // TODO: add optional parameters.
                MessageMarketPriceList.SendMessage();
                // doesnt exist yet MessageMarketPriceList.SendMessage();
            }

**Comment by midspace** [comment]
Ah, file is there. just forgot to sync into .csproj file.

**Comment by jpcsupplies** [comment]
ya i figured but the pink flying elephants got in the way of the screen before i could check the folder

**Comment by midspace** [comment]
Damn those pink :elephant:

**Comment by jpcsupplies** [comment]
Ok, so all we need now is the uuuhm...
"tools"  "ore" "ingot" and "component"  parameters..  and this one is totally done too..

Well that and keen fixing the mission box scroll bar.

**Comment by jpcsupplies** [comment]
Had a crack at adding the above parameters, but weird stuff kept happening in the warnings window, and adding a proto to the message sub failed entirely so i reverted the lot. 

Left a quick comment listing the parameters tho.
Was just going to use a simple split.length to see if any parameters were used, and ignore them if it wasn't something we expected.  Seemed overkill for a regex where we only expect a single string.

**Comment by midspace** [comment]
I considered added groupings to the price list. The formatting supports it now.

**Comment by jpcsupplies** [comment]
ok looks like i just need to update the help/documentation and thats our milestone nailed.  Great work.
