### ISSUE TITLE
Exception using /buy  and /value and balances reset

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#72]
On Ramblers Frontier server getting following error reports from players

zannador: An exception has been logged in the Economy client file
zannador: EconomyClient.log

Not so concerned about balances being reset, although we probably should improve data integrity there somehow..  (maybe have a bank balance file seperate so item changes dont risk curruption if we need to do a database reset/delete for items)

But in the workshop test build the following commands cause errors.
/buy 1 uranium ingot

/buy 100 interior

/value Steel Plate

/value ice

About to test here locally to get that log file.

**Comment by jpcsupplies** [comment]
log here https://gist.github.com/jpcsupplies/15419d69d1f0a656e000

**Comment by midspace** [comment]
yeah, I thought I had done something wrong with that code. I'm fixing it now.

**Comment by midspace** [comment]
Change https://github.com/jpcsupplies/Economy_mod/commit/ce146daede53fc1d6deb3556e201f33eba187c55 fixes this issue.

**Comment by jpcsupplies** [comment]
If you have pushed that fix to the workshop testing release, remember to restart the ramblers server or ask dragon or zannador to do it when server is empty next

**Comment by midspace** [comment]
It only affects the client. Server side is fine.
