### ISSUE TITLE
TODO: note to self  /ver command for debugging what build is on a server

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#73]
I noticed some of the new commands on the dev workshop build are missing, so at a guess its running an out of date build...   a ver command would be useful there if we remember to update it.. ill add one later  probably just be a basic:

/ver
lookup constant econver
reply to player in game

**Comment by midspace** [comment]
Change https://github.com/jpcsupplies/Economy_mod/commit/ce146daede53fc1d6deb3556e201f33eba187c55 adds the version number to the log files of both client and server.

**Comment by jpcsupplies** [comment]
Added a ver command too, which pulls our version number and our milestone string in front too.
If you are adding it to logging too, close this when its done, i notice you reverted it.. so ye :)

**Comment by jpcsupplies** [comment]
nevermind you reverted the revert my misread...  should be done then

**Comment by midspace** [comment]
yeah. Windows Github client, irritating. :anger:
