### ISSUE TITLE
BUG: LCD readouts blank

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#75]
Updated to Saturday build, looks like the price LCDs in blue mining are now blank.

**Comment by midspace** [comment]
Lcd is acting right.
Please check again online.

**Comment by jpcsupplies** [comment]
Suspected data issue, i may have to backup the data bank balances xml and delete?  The screens have the tags, they were working prior to the 30th commit.

**Comment by midspace** [comment]
Taken in game right now.
Tags need to be added to the Screen.

![2015-11-02_00001](https://cloud.githubusercontent.com/assets/6026063/10873198/de2a35cc-8164-11e5-9dae-fcc1664e11d6.jpg)

**Comment by jpcsupplies** [comment]
Found the issue
Tested here at shop -  previous version tags were detected in public title, (that is why blue mining is blank now) for some reason in this version they are only detected in the private title now.
On the space station I had them in public title.
