### ISSUE TITLE
ENH Build Valuation: (Rename value to price) Make value command calculate block value of target

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#77]
To help dronefab inc to value his ships  i am thinking a quick hack would be to change the current value command to be called "price"    and make the value command add up all the block types and calculate the combined value of the ship based on the sell price of all the components.

Unless we can access the production queue costs tho, ill probably need to extend the xl spread sheet to generate a block cost table to work off - doing it this way may prevent custom blocks being valued however.

**Comment by jpcsupplies** [comment]
Could also make value work so that it values targetted item if no parameters given, or values specified item if parameter is given

**Comment by jpcsupplies** [comment]
Wiki also lists this:
It allows players to value the worth of a cargo in a ship etc (eg /worth)  ... (or /cargo, or /value cargo etc)

It could also accept a parameter, for example a material name.  So if you have a ship with three full cargo containers, one has iron ingots, one has ice, and one has stone
point at ship and go /worth ice    for the script to retrieve the number of ice in the targeted ship, and then respond with the total value to buy or sell that amount.   
(say we detect 10000 ice, we could call our existing /value 10000 ice   sub routine to handle the reply to player)

**Comment by jpcsupplies** [comment]
Ok, biggest issue i see here, is there is simply too many items to account for.  I can manually add them all up in the spread sheet; but it will take quite a lot of time to key in all the build components.

What we need is a way to query via the API system the construction requirements of a given block/object blueprint.

Anything useful exposed in API whitelist?

**Comment by midspace** [comment]
I haven't noted this anywhere, but /worth currently ignores all owner checks.
You can use it on any ship.
As i have set it up to display the list of components, we should either limit usage to ships people mostly own, or remove the compontent list *if* you don't own it.

Also, i have used the market Sell price for all components. Thought I should double check this.

**Comment by jpcsupplies** [comment]
ah ok so it gives you a recommended retail price on the value of your cargo..  perfect for roving traders :)

I think valuing another players ship (minus cargo value)  is fine.   Allows people to see what a ship is worth and make an offer, or decide if an existing offer from the current owner is fair. Should work well.

**Comment by midspace** [comment]
Currently cargo is calculated. Should I separate it?
ie., subtotal. Total?

**Comment by jpcsupplies** [comment]
subtotal? sounds good
cargos should only show to the main owner tho..    not to someone scouting a ship just to see if it is worth stealing etc

**Comment by jpcsupplies** [comment]
this feature is looking good so far, i know we need to tweak some stuff like valuations outside of trade zone but if players are trading ships there anyway, thats not hurting anything.. im looking at pushing out a progress update to the public version of the mod..   i think the only thing making me pause is to check if we have a set command for altering the npc default trade zone(s)

**Comment by jpcsupplies** [comment]
I think this item is all done now..  wanna confirm and close when you get a sec.
