### ISSUE TITLE
(Misc) Testing Planetfall Survey Ship

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#82]
Just a reminder to midspace that I asked if they could confirm if my survey ship has adequate thrust to launch from a planet in its current configuration.

Landing instructions -
Presumably use the hydrogen thrust with dampeners to halt your descent and carefully settle on the ground onto the wheels.  I am unsure if i will need additional small thrust here for stability.  You may need to turn the ship on its horizontal plane to use the rear thrust to cancel out any parallel momentum in relation to the ground.

Launch instructions:   
While landed on a planet, and sitting on the landing wheels, enabled all hydrogen thrust, depress space bar to lift off the surface, then tilt nose up approximately 10 to 15 degress, and also depress the W key in addition to the space bar to engage forward thrust and have it contribute to the upward momentum.   The Gas tanks hold roughly 6 to 10 minutes of fuel (untested) which hopefully gets you to space without an uncheduled "durability test" to see how well my ship "bounces"..

**Comment by jpcsupplies** [comment]
Reportedly my ship is more fall..  than fly ..

have to work out how much underpowered it is then :/

What if you jettison the Delta up front ?   probably wont help much but its all heavy armor.

**Comment by midspace** [comment]
I'd suggest adding 4 more thrusters on the bottom of the new type that is coming, and putting 2 hydrogen thrusters on the back.

BTW, planets are coming in this week's update.
http://forums.keenswh.com/forums/general-discussion.313748/

**Comment by jpcsupplies** [comment]
hmm i can put  lander in my hangar maybe with turbines and a booster
btw can you push out our test build to your test mod, i got black list toggling working

**Comment by midspace** [comment]
tonight.

**Comment by jpcsupplies** [comment]
signing NDA atm.. so this may be interesting

**Comment by midspace** [comment]
:grin:

**Comment by jpcsupplies** [comment]
still no reply probably wont get my keys until official planets release anyway

ive added more thrusters to survey ship.. if you are bored jettison the delta transport and the weapons pod and give it another crack at landing

**Comment by jpcsupplies** [comment]
Confirmed - current configuration lands ok,  although i jettisoned the gun pod and delta ship first which amusingly fell to earth almost poetically before bouncing 12 times and destroying itself.

**Comment by midspace** [comment]
Now, create a DS on this version, and test the econ mod on it, to make sure it still spawns goods and takes them away.

**Comment by jpcsupplies** [comment]
LCDs seem to run, and i was able to get a few econ commands to fire, although i was busy at the time trying not to crash into a large gravity well at the time...  *chuckles*
