### ISSUE TITLE
ENH: seen command does substring search (ie /seen fox also matches player winfox)

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#83]
Can we get the seen command to do a substring search on not found.

eg /seen fat   would also match big_fat_mumma if no other player was called "fat"

**Comment by jpcsupplies** [comment]
a date parameter might be handy too..   
/seen #today | #week  for example could show names of players, or a stat summary in the last 24 hours. or week

**Comment by jpcsupplies** [comment]
today or week might be an admin only function actually..  in which case the filter is probably better in the /accounts command.
eg /accounts today  would show any accounts active today

**Comment by midspace** [comment]
Code change https://github.com/jpcsupplies/Economy_mod/commit/c1a0bd66b0be377609cf1b13d03ecd2a215a0d2b will only pull back the first one with the substring of "fat".
Unless that is what you want, it would make sense to count the number of results and change the output if there is more than 1.

**Comment by jpcsupplies** [comment]
It's only meant as a basic user friendly enhancement to seen, just to save players having to remember a players entire name; the seen command is a player command, so first instance is fine -  if we made it too informative it would effectively function as a way for players to get /accounts like information, and id rather not make it too easy for players to take a crack at exploring issue #20 

That's why i moved the date parameter idea to #107 instead

Be nice if the search was case insensitive tho; but that gave some really odd messages when I tried to do that a few different ways.  It could probably still work if i did it a more long winded way, but I didn't want anything too sim heavy, or code reading unfriendly.    The current solution is both simple, and should have virtually no effect on performance, with the trade off that its case sensitive - which is probably a good thing,  ie - StarFox +  ArfBarf   /seen arF  = StarFox  /seen Arf = ArfBarf  etc
