### ISSUE TITLE
Configuration to limit to money transaction

### ISSUE THREAD

**Issue by midspace** [jpcsupplies/Economy_mod#85]
3:01 AM - HurricaneGirl: Hey there!! I am the one that was asking for a basic economy module. How hard would it be for me to remove the buy, sell and value commands from Frontier in order to have the functionaility I am looking for? And thank you! You do such great work!!

**Comment by jpcsupplies** [comment]
/set trade off   is probably the command we need to make work - i considered a suspend trade option in a previous post; that would limit economy to person to person pay only like our pre-alpha release

**Comment by jpcsupplies** [comment]
Just a thought if we deleted all NPC zones, its basically doing this anyway.

That leaves the worth command but that was just a value estimation anyway.
The value command would fail as there was no zone in range to draw on for price.  But players could still trade/pay each other.

Wanna pass that on to HurricaneGirl ?
