### ISSUE TITLE
Discuss -

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#90]
you see this
http://forums.keenswh.com/threads/wico-antenna-network-wan.7372286/

reminds me of something we were talkin about..

**Comment by midspace** [comment]
I think you're going to have to remind me.

**Comment by jpcsupplies** [comment]
Our system using antennas to access remote markets etc which we couldnt use because we had no way to detect when something was in antenna range and/or repeaters.
This script sends data over an antenna network.. it literally sends the data, as opposed to us simulating it by detecting the presence of a transmitter. or something like that.

**Comment by midspace** [comment]
The basic concept of the WICO, is a ship borne communication.
It doesn't include the player.

**Comment by midspace** [comment]
I don't want to try and replicate what WICO does.
If we were to replicate code. It should be logic in the Game itself.

**Comment by jpcsupplies** [comment]
Only way we could use it would be to detect that an antenna can communicate with an antenna in the market, on confirmation detect the antennas location and then cheat a little and just make our range check key to that antenna position..   Although with your LCD logic, we probably dont need to as urgently anymore - although we could take advantage of your codes ability to register the same market in more than one coordinate using some sort of antenna wizardry.

Actually a really big cheat here would be simply checking our registered markets, and checking how far the coordinates are from each other.  The antennas used for expanding a trade region need only have some [name] keyword like lcds, and we dont need any keen code at all, except perhaps to check the antenna is turned on.  So we can simulate the effect, but its not really urgent.

How are we looking for our milestone...  hmm mission box bug is holding up the request price list thing.  

Other issue was the request a payment feature; for in effect sending a player a bill;

* player bob has requested you pay them XXx credits for "flying you to the moon"  /accept charge or /deny 

Wouldn't mind getting that global message thing working too. I made a start but got way side tracked with real life and CTG stuff.

How hard would it be to make a module that can be called to display a message to all connected players in a mission box, eg msgall.send("hello world");

Doesnt really need to be more complicated than that; and could be used for the news or event/mission system later down the line if we decide to add that.

Also a gifting system - ie all players on next connect get given a particular item. (or ship?) Dont want one yet, just bouncing the idea off you. Would need to know if the player got given one already in a previous connect and not give them a second one.
