### ISSUE TITLE
Missing pricing

### ISSUE THREAD

**Issue by midspace** [jpcsupplies/Economy_mod#95]
Waiting on pricing for the new tools.

```
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>PreciseAutomaticRifleItem</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>RapidFireAutomaticRifleItem</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>UltimateAutomaticRifleItem</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>Welder2Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>Welder3Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>Welder4Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>AngleGrinder2Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>AngleGrinder3Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>AngleGrinder4Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>HandDrill2Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>HandDrill3Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
    <MarketItem>
      <TypeId>MyObjectBuilder_PhysicalGunObject</TypeId>
      <SubtypeName>HandDrill4Item</SubtypeName>
      <Quantity>0</Quantity>
      <SellPrice>1</SellPrice>
      <BuyPrice>1</BuyPrice>
      <IsBlacklisted>true</IsBlacklisted>
    </MarketItem>
```

**Comment by jpcsupplies** [comment]
Ahh ill have to figure out component costs then.. job for later tonite

**Comment by jpcsupplies** [comment]
ugh falling asleep again have to do more in mmorning

**Comment by jpcsupplies** [comment]
Ok i cant identify the drills but here is where i am - 
precise rifle, sell price $12.84,  buy price (combined buy component value) approx $2.52

rapid rifle, sell price $13.43,  buy price (as calculated or) $3.05

Ultimate automatic rifle, sell price $15.94, buy price (as calculated or) $5.28

Enhanced welder, sell price $11.36,  buy price (as calculated or) $1.21

Proficient welder, sell price $11.84, buy price (as calculated or) $$1.63

Elite Welder, sell price $12.16, buy price as calculated or $1.92

Enhanced grinder, sell price $13.55,  buy price as calculated or $3.15

Proficient grinder sell $12.83,  buy $2.47

Enhanced drill sell $13.73, buy $3.32

proficient drill sell $14.97, buy $4.42

Also have to re value the tools and ice, the build costs/availabilty were changed -
welder sell $10.93,  buy $0.83

Rifle sell 10.73, buy $0.65

Grinder sell $11.92, buy $1.71

Drill sell 16.11  buy 5.43

Ice sell 0.337  buy 0.299

**Comment by jpcsupplies** [comment]
When i say as calculated i mean the buy cost should be the combined buy cost of its components (in this case ingots)

It might be worth setting all components buy cost to be the ingot value automatically in the next release.  Then we really only need worry about ore pricing if they add new items.

Sell price could be a formula, much like my xl sheet, 
For ores
if buy cost per unit is under 0.5 use 64% markup (multiply by 1.64) for sell
if buy cost per unit is between 0.5 and 1, use 56% markup (multiply by 1.56) for sell
if buy cost per unit is between 1 and 2, use 32% markup (multiply by 1.32) for sell
if buy cost per unit is between 2 and 5, use 24% markup (multiply by 1.24) for sell
if buy cost per unit is 5 or up use flat 11% markup for sell (multiply by 1.11)

For ingots 
Use value of ore required to make a unit of ingot.  
For buy multiply buy by ore buy, for sell multiply sell by ore sell.

For components
Use value of ingots required to make a single unit of that component.
For buy multiply ingots buy price by ingots needed, for sell multiply ingots sell price by ingots needed.

For tools
For buy price calculate buy value of ingots needed 
For sell calculate sell value of ingots needed PLUS 10

**Comment by jpcsupplies** [comment]
elite grinder sell $13.16, buy $2.76
elite drill sell $14.97, buy $4.42
